CREATE TABLE packet_captures (
    "Protocol" INTEGER,
    "Flow Duration" DOUBLE PRECISION,
    "Total Fwd Packets" INTEGER,
    "Total Backward Packets" INTEGER,
    "Fwd Packets Length Total" DOUBLE PRECISION,
    "Bwd Packets Length Total" DOUBLE PRECISION,
    "Fwd Packet Length Max" DOUBLE PRECISION,
    "Fwd Packet Length Min" DOUBLE PRECISION,
    "Fwd Packet Length Mean" DOUBLE PRECISION,
    "Fwd Packet Length Std" DOUBLE PRECISION,
    "Bwd Packet Length Max" DOUBLE PRECISION,
    "Bwd Packet Length Min" DOUBLE PRECISION,
    "Bwd Packet Length Mean" DOUBLE PRECISION,
    "Bwd Packet Length Std" DOUBLE PRECISION,
    "Flow Bytes/s" DOUBLE PRECISION,
    "Flow Packets/s" DOUBLE PRECISION,
    "Flow IAT Mean" DOUBLE PRECISION,
    "Flow IAT Std" DOUBLE PRECISION,
    "Flow IAT Max" DOUBLE PRECISION,
    "Flow IAT Min" DOUBLE PRECISION,
    "Fwd IAT Total" DOUBLE PRECISION,
    "Fwd IAT Mean" DOUBLE PRECISION,
    "Fwd IAT Std" DOUBLE PRECISION,
    "Fwd IAT Max" DOUBLE PRECISION,
    "Fwd IAT Min" DOUBLE PRECISION,
    "Bwd IAT Total" DOUBLE PRECISION,
    "Bwd IAT Mean" DOUBLE PRECISION,
    "Bwd IAT Std" DOUBLE PRECISION,
    "Bwd IAT Max" DOUBLE PRECISION,
    "Bwd IAT Min" DOUBLE PRECISION,
    "Fwd PSH Flags" INTEGER,
    "Bwd PSH Flags" INTEGER,
    "Fwd URG Flags" INTEGER,
    "Bwd URG Flags" INTEGER,
    "Fwd Header Length" DOUBLE PRECISION,
    "Bwd Header Length" DOUBLE PRECISION,
    "Fwd Packets/s" DOUBLE PRECISION,
    "Bwd Packets/s" DOUBLE PRECISION,
    "Packet Length Min" DOUBLE PRECISION,
    "Packet Length Max" DOUBLE PRECISION,
    "Packet Length Mean" DOUBLE PRECISION,
    "Packet Length Std" DOUBLE PRECISION,
    "Packet Length Variance" DOUBLE PRECISION,
    "FIN Flag Count" INTEGER,
    "SYN Flag Count" INTEGER,
    "RST Flag Count" INTEGER,
    "PSH Flag Count" INTEGER,
    "ACK Flag Count" INTEGER,
    "URG Flag Count" INTEGER,
    "CWE Flag Count" INTEGER,
    "ECE Flag Count" INTEGER,
    "Down/Up Ratio" DOUBLE PRECISION,
    "Avg Packet Size" DOUBLE PRECISION,
    "Avg Fwd Segment Size" DOUBLE PRECISION,
    "Avg Bwd Segment Size" DOUBLE PRECISION,
    "Fwd Avg Bytes/Bulk" DOUBLE PRECISION,
    "Fwd Avg Packets/Bulk" DOUBLE PRECISION,
    "Fwd Avg Bulk Rate" DOUBLE PRECISION,
    "Bwd Avg Bytes/Bulk" DOUBLE PRECISION,
    "Bwd Avg Packets/Bulk" DOUBLE PRECISION,
    "Bwd Avg Bulk Rate" DOUBLE PRECISION,
    "Subflow Fwd Packets" INTEGER,
    "Subflow Fwd Bytes" DOUBLE PRECISION,
    "Subflow Bwd Packets" INTEGER,
    "Subflow Bwd Bytes" DOUBLE PRECISION,
    "Init Fwd Win Bytes" DOUBLE PRECISION,
    "Init Bwd Win Bytes" DOUBLE PRECISION,
    "Fwd Act Data Packets" INTEGER,
    "Fwd Seg Size Min" DOUBLE PRECISION,
    "Active Mean" DOUBLE PRECISION,
    "Active Std" DOUBLE PRECISION,
    "Active Max" DOUBLE PRECISION,
    "Active Min" DOUBLE PRECISION,
    "Idle Mean" DOUBLE PRECISION,
    "Idle Std" DOUBLE PRECISION,
    "Idle Max" DOUBLE PRECISION,
    "Idle Min" DOUBLE PRECISION
);
